package com.cris.cmsm.database;

import android.database.sqlite.SQLiteDatabase;

import com.cris.cmsm.dao.DivisionDao;
import com.cris.cmsm.dao.RailwayDao;
import com.cris.cmsm.models.Division;
import com.cris.cmsm.models.Railway;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig railwayDaoConfig;
    private final DaoConfig divisionDaoConfig;

    private final RailwayDao railwayDao;
    private final DivisionDao divisionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        railwayDaoConfig = daoConfigMap.get(RailwayDao.class).clone();
        railwayDaoConfig.initIdentityScope(type);

        divisionDaoConfig = daoConfigMap.get(DivisionDao.class).clone();
        divisionDaoConfig.initIdentityScope(type);

        railwayDao = new RailwayDao(railwayDaoConfig, this);
        divisionDao = new DivisionDao(divisionDaoConfig, this);

        registerDao(Railway.class, railwayDao);
        registerDao(Division.class, divisionDao);
    }
    
    public void clear() {
        railwayDaoConfig.getIdentityScope().clear();
        divisionDaoConfig.getIdentityScope().clear();
    }

    public RailwayDao getRailwayDao() {
        return railwayDao;
    }

    public DivisionDao getDivisionDao() {
        return divisionDao;
    }

}
