package com.cris.cmsm.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIVISION.
 */
public class Division {

    private Long id;
    private String divcode;
    private String sname;
    private String fname;
    private String rlycode;
    private String divid;
    private String electrifiedflag;
    private String divflag;

    public Division() {
    }

    public Division(Long id) {
        this.id = id;
    }

    public Division(Long id, String divcode, String sname, String fname, String rlycode, String divid, String electrifiedflag, String divflag) {
        this.id = id;
        this.divcode = divcode;
        this.sname = sname;
        this.fname = fname;
        this.rlycode = rlycode;
        this.divid = divid;
        this.electrifiedflag = electrifiedflag;
        this.divflag = divflag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDivcode() {
        return divcode;
    }

    public void setDivcode(String divcode) {
        this.divcode = divcode;
    }

    public String getSname() {
        return sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getRlycode() {
        return rlycode;
    }

    public void setRlycode(String rlycode) {
        this.rlycode = rlycode;
    }

    public String getDivid() {
        return divid;
    }

    public void setDivid(String divid) {
        this.divid = divid;
    }

    public String getElectrifiedflag() {
        return electrifiedflag;
    }

    public void setElectrifiedflag(String electrifiedflag) {
        this.electrifiedflag = electrifiedflag;
    }

    public String getDivflag() {
        return divflag;
    }

    public void setDivflag(String divflag) {
        this.divflag = divflag;
    }

}
