package com.cris.cmsm.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RAILWAY.
 */
public class Railway {

    private Long id;
    private String rlycode;
    private String sname;
    private String fname;
    private String flag;

    public Railway() {
    }

    public Railway(Long id) {
        this.id = id;
    }

    public Railway(Long id, String rlycode, String sname, String fname, String flag) {
        this.id = id;
        this.rlycode = rlycode;
        this.sname = sname;
        this.fname = fname;
        this.flag = flag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRlycode() {
        return rlycode;
    }

    public void setRlycode(String rlycode) {
        this.rlycode = rlycode;
    }

    public String getSname() {
        return sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

}
