package com.cris.cmsm.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.cris.cmsm.database.DaoSession;
import com.cris.cmsm.models.Division;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DIVISION.
*/
public class DivisionDao extends AbstractDao<Division, Long> {

    public static final String TABLENAME = "DIVISION";

    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Divcode = new Property(1, String.class, "divcode", false, "DIVCODE");
        public final static Property Sname = new Property(2, String.class, "sname", false, "SNAME");
        public final static Property Fname = new Property(3, String.class, "fname", false, "FNAME");
        public final static Property Rlycode = new Property(4, String.class, "rlycode", false, "RLYCODE");
        public final static Property Divid = new Property(5, String.class, "divid", false, "DIVID");
        public final static Property Electrifiedflag = new Property(6, String.class, "electrifiedflag", false, "ELECTRIFIEDFLAG");
        public final static Property Divflag = new Property(7, String.class, "divflag", false, "DIVFLAG");
    }


    public DivisionDao(DaoConfig config) {
        super(config);
    }
    
    public DivisionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String sql = "CREATE TABLE " + (ifNotExists? "IF NOT EXISTS ": "") + "'DIVISION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DIVCODE' TEXT," + // 1: divcode
                "'SNAME' TEXT," + // 2: sname
                "'FNAME' TEXT," + // 3: fname
                "'RLYCODE' TEXT," + // 4: rlycode
                "'DIVID' TEXT," + // 5: divid
                "'ELECTRIFIEDFLAG' TEXT," + // 6: electrifiedflag
                "'DIVFLAG' TEXT);"; // 7: divflag
        db.execSQL(sql);
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DIVISION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Division entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String divcode = entity.getDivcode();
        if (divcode != null) {
            stmt.bindString(2, divcode);
        }
 
        String sname = entity.getSname();
        if (sname != null) {
            stmt.bindString(3, sname);
        }
 
        String fname = entity.getFname();
        if (fname != null) {
            stmt.bindString(4, fname);
        }
 
        String rlycode = entity.getRlycode();
        if (rlycode != null) {
            stmt.bindString(5, rlycode);
        }
 
        String divid = entity.getDivid();
        if (divid != null) {
            stmt.bindString(6, divid);
        }
 
        String electrifiedflag = entity.getElectrifiedflag();
        if (electrifiedflag != null) {
            stmt.bindString(7, electrifiedflag);
        }
 
        String divflag = entity.getDivflag();
        if (divflag != null) {
            stmt.bindString(8, divflag);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Division readEntity(Cursor cursor, int offset) {
        Division entity = new Division( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // divcode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fname
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // rlycode
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // divid
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // electrifiedflag
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // divflag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Division entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDivcode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFname(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRlycode(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDivid(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setElectrifiedflag(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDivflag(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected Long updateKeyAfterInsert(Division entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Division entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
